tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
brew "mas"
brew "mysql-client"
brew "vim"
brew "yarn"
brew "zsh"
cask "1password"
cask "docker"
cask "firefox"
cask "google-chrome"
cask "iterm2"
cask "jetbrains-toolbox"
cask "notion"
cask "station"
cask "visual-studio-code"
mas "Xcode", id: 497799835
