tap "heroku/brew"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
brew "bitrise"
brew "carthage"
brew "krb5"
brew "libpq"
brew "nodenv"
brew "mas"
brew "mysql-client"
brew "putty"
brew "sqlite"
brew "python@3.10"
brew "rbenv"
brew "ruby"
brew "vim"
brew "yarn"
brew "zplug"
brew "zsh"
brew "heroku/brew/heroku"
cask "1password"
cask "docker"
cask "figma"
cask "firefox"
cask "google-chrome"
cask "iterm2"
cask "jetbrains-toolbox"
cask "ngrok"
cask "notion"
cask "slack"
cask "stoplight-studio"
cask "visual-studio-code"
cask "zoom"
mas "DaisyDisk", id: 411643860
mas "WinArchiver Lite", id: 414855915
mas "Xcode", id: 497799835
